#' Ask Gemini
#'
#' Note: See also `reset_chat_session`.
#'
#' @param question The question to ask Gemini.
#'
#' @examples
#' \dontrun{
#' cat(ask_gemini("What do you think about R language?"))
#' }
#'
#' @return A character value with the response generated by Gemini.
#'
#' @export
#'
ask_gemini <- function(question) {
  # Get the existing chat session messages, and add the new message.
  chat_session_messages <- append(get_chat_session(), list(
    list(role = "user", parts = list(text = question))
  ))
  # Send the query to Gemini.
  gemini_reply <- parse_response(gemini_conversation(question, session = chat_session_messages))
  chat_session_messages <- append(chat_session_messages, list(
    list(role = "model", parts = list(text = gemini_reply))
  ))
  # Update the chat session messages with the new question and the reply.
  reset_chat_session(chat_session_messages)
  gemini_reply
}
